// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// compute_contour_vals
Eigen::VectorXd compute_contour_vals(const Eigen::MatrixXd& marks, const Eigen::VectorXd& now_rates, const Eigen::MatrixXd& now_seeds);
RcppExport SEXP _plotmaps_compute_contour_vals(SEXP marksSEXP, SEXP now_ratesSEXP, SEXP now_seedsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type marks(marksSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type now_rates(now_ratesSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type now_seeds(now_seedsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_contour_vals(marks, now_rates, now_seeds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plotmaps_compute_contour_vals", (DL_FUNC) &_plotmaps_compute_contour_vals, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_plotmaps(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
