# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title compute contour vals for each pixel
#'
#' @description compute one contour, by filling in each of the pixels/marks
#'
#' @param marks matrix of pixels
#' @param now_rates the rate of each voronoi tile
#' @param now_seeds the locations of each voronoi tile
#'
#' @return values vectoring storing the value for each pixel
#'
#' @export
compute_contour_vals <- function(marks, now_rates, now_seeds) {
    .Call('_plotmaps_compute_contour_vals', PACKAGE = 'plotmaps', marks, now_rates, now_seeds)
}

